[build]
  command   = "next build && next-on-netlify"
  functions = "__next_functions"
  publish   = "__next_publish"

[[plugins]]
  package = "netlify-plugin-image-optim"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

	[plugins.inputs]
    baseUrl = "https://covidagora.hitechline.com.br"
    sitemapPath = "/sitemap.xml"
    providers = [
      "google"
    ]